Fix ElementList.__getattr__() to no longer hide ElementNotFound
When elements aren't found on the page, calling methods like
ElementList.click() don't raise ElementNotFound. Instead it would report
"AttributeError: 'ElementList' object has no attribute 'click'"

The current behavior is confusing because it reports the wrong error.
Users start looking why there is an AttributeError instead of noticing
that the ElementNotFound exception was the actual cause.